### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by Astraxx04** [Genesis-ISE-DSCE/Catalysis2.0#34]
Using the mascot try to create an animated effect when the webpage loads. You are free to try anything.

**Comment by Maahipal27** [comment]
@Astraxx04 Please assign  me the issue I want to work on it.

**Comment by Maahipal27** [comment]
@Astraxx04 I have made the pull request please review it.

**Comment by Maahipal27** [comment]
@Astraxx04 you didn't reviewed my pull request?I have made a pull request please go through it.

**Comment by Maahipal27** [comment]
@Astraxx04 ?? please review my PR
