### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by Astraxx04** [Genesis-ISE-DSCE/Catalysis2.0#9]
Refer to the figma link provided in readme.

**Comment by beatrizsmerino** [comment]
Hello!!, 😊
I want to participate to fix this problem, can you assign me the task?

**Comment by Saakshi-Shenoy** [comment]
Hey! I'd like to work on this issue, could you assign the task to me ?

**Comment by shagundubey29** [comment]
I would to contribute to this

**Comment by shagundubey29** [comment]
assign to me this
